name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      # - uses: actions/checkout@v4
      # - uses: oven-sh/setup-bun@v2
      # - run: bun install
      # - run: SECRET=${{ secrets.SECRET }} bun run build
      # - name: publish deps
      #   uses: appleboy/scp-action@v0.1.4
      #   with:
      #     source: ./node_modules/*
      #     host: ${{ secrets.SSH_HOST }}
      #     target: ${{ secrets.SSH_PATH }}/node_modules
      #     username: ubuntu
      #     rm: true
      #     strip_components: 2
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: run in ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ secrets.SSH_PATH }} && git reset --hard && git pull origin main && /home/ubuntu/.bun/bin/bun install && /home/ubuntu/.bun/bin/bun run prisma migrate deploy && /home/ubuntu/.bun/bin/bun run prisma generate && /home/ubuntu/.bun/bin/bun run build && pm2 restart agentify
