name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: SECRET=${{ secrets.SECRET }} bun run build
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish Deps
        uses: appleboy/scp-action@v0.1.4
        with:
          source: ./node_modules/*
          host: ${{ secrets.SSH_HOST }}
          target: ${{ secrets.SSH_PATH }}/node_modules
          username: ubuntu
          rm: true
          key: ${{ secrets.SSH_PRIVATE_KEY }}
