name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-24.04
    steps:
      - name: run in ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_PATH }} && \
            git reset --hard && \
            git pull origin main && \
            /home/ubuntu/.bun/bin/bun install && \
            /home/ubuntu/.bun/bin/bun run prisma migrate deploy && \
            /home/ubuntu/.bun/bin/bun run prisma generate && \
            /home/ubuntu/.bun/bin/bun run build && \
            /home/ubuntu/.bun/bin/pm2 restart agentify
